# ####################
#
# CircleCI Job Filters
#
# ####################
build-filters: &build-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/

deploy-filters: &deploy-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

# ####################
#
# CircleCI steps
#
# ####################

docker-login: &docker-login
  name: Log into Docker Hub
  command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

# ####################
#
# CircleCI 2.0 Jobs
#
# ####################
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    working_directory: ~/cloc.me
    steps:
      - setup_remote_docker
      - checkout
      - run: make build
        # - run:
        #     name: make test-functional
        #     command: |
        #       python -m venv .venv
        #       source .venv/bin/activate
        #       pip install tox
        #       make test-functional
      - run: *docker-login
      - run: make push-ci
      # - run:
      #     name: Push to Docker Hub
      #     command: |
      #       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      #       make tag-latest
      #       make push
  lint:
    docker:
      - image: circleci/buildpack-deps:bionic
    working_directory: ~/cloc.me
    steps:
      - setup_remote_docker
      - checkout
      - run: *docker-login
      - run: make pull-ci
      - run: make test-lint

  unit-test:
    docker:
      - image: circleci/buildpack-deps:bionic
    working_directory: ~/cloc.me
    steps:
      - setup_remote_docker
      - checkout
      - run: *docker-login
      - run: make pull-ci
      - run: make test-unit

  functional-test:
    machine:
        image: circleci/classic:latest
    working_directory: ~/cloc.me
    steps:
      - checkout
      - run: *docker-login
      - run: make pull-ci
      - run: make test-functional

# ####################
#
# CircleCI Workflow
#
# ####################
workflows:
  version: 2
  cloc-me-workflow:
    jobs:
      - build:
          filters: *build-filters
      - lint:
          requires:
              - build
          filters: *build-filters
      - unit-test:
          requires:
              - build
          filters: *build-filters
      - functional-test:
          requires:
              - build
          filters: *build-filters
