# ####################
#
# CircleCI Job Filters
#
# ####################
build-filters: &build-filters
  tags:
    ignore: /.*/
  branches:
    only: /.*/

deploy-filters: &deploy-filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

# ####################
#
# CircleCI 2.0 Jobs
#
# ####################
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/cloc.me
    steps:
      - setup_remote_docker
      - checkout
      - run: make build
      - run: make test-lint
      - run: make test-unit
        # - run:
        #     name: make test-functional
        #     command: |
        #       python -m venv .venv
        #       source .venv/bin/activate
        #       pip install tox
        #       make test-functional
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            make tag-latest
            make push

# ####################
#
# CircleCI Workflow
#
# ####################
workflows:
  version: 2
  cloc-me-workflow:
    jobs:
      - build:
          filters: *build-filters
